# Generated by Django 2.2 on 2019-05-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=32)),
                ('amount_required', models.IntegerField()),
                ('business_type', models.CharField(choices=[('', 'Choose...'), ('FT', 'Food Truck'), ('CON', 'Construction'), ('OTH', 'Other')], max_length=3)),
                ('years_in_business', models.IntegerField()),
                ('other', models.CharField(max_length=64)),
                ('agree', models.BooleanField()),
            ],
        ),
    ]
