# Generated by Django 2.2.6 on 2019-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
    ]
