# Generated by Django 2.2.6 on 2019-11-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='secondary',
            field=models.CharField(default='null', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary',
            field=models.CharField(max_length=64),
        ),
    ]
